org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official

org.gradle.java.installations.paths=/data/data/com.termux/files/usr/lib/jvm/java-21-openjdk
org.gradle.java.installations.auto-detect=true
android.aapt2FromMavenOverride=/data/data/com.termux/files/home/android-sdk-full/android-sdk/build-tools/37.0.0/aapt2
